spring:
  profiles:
    active: dev

#mybatis config begin
mybatis:
  mapper_locations: classpath:mapper/*.xml
  type_aliases_package: com.vip.xpf.model
  configuration:
    cache_enabled: false
    map_underscore_to_camel_case: true

mapper:
  mappers: com.vip.xpf.dao.common.sql.ConditionsQueryMapper
#mybatis config end

#swagger config begin
swagger:
  enabled: true
  title: logic api文档
  description: logic api文档
  version: 1.0.0
  basePackage: com.vip.xpf.logic.controller
#swagger config end

---

spring:
  profiles: dev
  #DataSource config begin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver_class_name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.199.195.9:3306/vip-hhc-xpf?autoReconnect=true&autoReconnectForPools=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: lfuser
    password: vipshop147258
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 5000
  #DataSource config end

  #redis config begin
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      #默认过期时间（毫秒）
      time_to_live: 300000
  #redis config end

