spring:
  profiles:
    active: dev

#mybatis config begin
mybatis:
  mapper_locations: classpath:mapper/*.xml
  type_aliases_package: com.vip.xpf.model
  configuration:
    cache_enabled: false
    map_underscore_to_camel_case: true
#mybatis config end

mapper:
  mappers: com.vip.xpf.dao.common.ConditionsQueryMapper

swagger:
  enabled: true
  title: logic api文档
  description: logic api文档
  version: 1.0.0
  basePackage: com.vip.xpf.controller

---
#DataSource config begin
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver_class_name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.199.195.9:3306/vip-hhc-xpf?autoReconnect=true&autoReconnectForPools=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: lfuser
    password: vipshop147258
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 5000

#DataSource config end
